# Site settings
title: Spencer Moore
# twitter_username: twitterUsername
name: Spencer Moore

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
# - title: Blog
   #url: http://blogname.blogspot.com/
 - title: GitHub
   url: https://github.com/ProgramMeThis
# - title: StackOverflow
#   url: https://stackoverflow.com/
 - title: LinkedIn
   url: https://www.linkedin.com/in/spencer-moore-7554804

#Any buzzword skills you want to include
skills:
 - C#
 - .Net
 - Visual Source Safe
 - Team Foundation Server
 - PowerShell
 - Active Directory
 - BASH Scripting
 - SQL
 - SQL Server
 - BIRT
 - Crystal Reports
 - SSRS
 - Power BI
 - IBM Maximo
 - Microsoft Dynamics SL
 - Cornerstone Learning Management System

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://blogtitle.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Application Support Manager 
   start: 2019
   end: Ongoing
   employer: Grand River Dam Authority
   description: With this new role my focus has shifted from managing the help desk and software support team to only managing the software support team. This has allowed me to focus more on the software support and development side of things so that I can provide even better customer service on that side.
 - title: Manager of IT Solution Services 
   start: 2015
   end: 2019
   employer: Grand River Dam Authority
   description: I managed two main parts of IT; software support and help desk. With both of those groups being under the same direct manager we were able to work seamlessly together and ensure things ran smoothly. In this position I was what I like to call a "Working Manager." I would not only manage the individuals but would also do the work of helping out with the help desk as well as writing/supporting software to meet GRDA's needs. This ranged from developing C# desktop applications to writing PowerShell scripts and helping support our big purchased products like Maximo and Dynamics SL.
 - title: Superintendent of Application and Development 
   start: 2013
   end: 2015
   employer: Grand River Dam Authority
   description: I managed the corporate IT department which included the support desk and the software developers. Along with my managerial role I still wrote C# software. I mainly wrote windows forms applications, but still continued to write some asp.net webapps. As with my previous position I still was the primary support for Microsoft Dynamics SL and the backup support for Maximo by IBM.
 - title: Assistant Superintendent Programmer
   start: 2009
   end: 2013
   employer: Grand River Dam Authority
   description: I wrote mainly small applications to fulfill various needs. These applications were all done in C# and used a SQL Server backend when necessary. Most of them so were desktop applications, but my last project in this position was a large asp.net web app. While developing applications I also was the initially the backup support and then became the primary support for Microsoft Dynamics SL and was also backup support for IBM Maximo Asset Management.

#Education is required
education:
 - level: Bachelor of Science
   date: 2009
   subject: Information Systems Technology
   school: University of Tulsa
   description: While at the University of Tulsa I majored in Information Systems Technology. This consisted of courses from both the college of business and the college of engineering. This meant I got a more well-rounded view of software development and databases. Java was the programming language that was taught throughout the courses I took and Oracle was the database engine that was taught. The engineering courses looked at things from a more scientific perspective and covered programming as it relates to that. This included learning various sorting algorithms and solving different problems such as the bin packing problem. The business courses looked at things from a more business perspective. This involved using scenarios that you might encounter in the business world, such as developing a database that would house employee data.

#List of interesting Github repo/projects to include - optional
github:
 - ProgramMeThis/Dell-Warranty-Checker
 - ProgramMeThis/SQL-Server-Index-Manager

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/
#   flairimageurl: http://stackoverflow.com/users/flair/

intro: |
  I am a software developer with over 10 years experience working in various facets of IT. Along with developing software I've been managing development/support teams, automating business processes and helping support purchased products such as IBM's Maximo, Microsoft Dynamics SL and Cornerstone Learning Management System. My biggest passion is helping make people's lives easier with the power of technology. Whether that's writing software, buying something off the shelf or simply getting more use out of what you already have there's almost always some room for improvement.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>C#/.Net</strong>: Most of my career has been spent developing applications with .Net and more specifcally C#. The first few years were spent solely developing Windows Forms applications but as web applications became more popular the switch was made to using ASP.net for the primary development platform with some integrations being solved with Windows services. <br/><br/>
   <strong>SQL</strong>: SQL and more specifically SQL Server has been a part of everything I've done in the past 10 years. All of the applications I have developed or pruchased products I have implemented have used SQL server for their backend data storage.<br/><br/>
   <strong>PowerShell</strong>: With part of my time being spent overseeing the help desk along side the software developers, there have been countless times where I've developed a PowerShell script to make the Help Desk more efficient. This ranges from somethign as simple as starting/stopping windows services to completly enabling and setting up BitLocker.<br/><br/>
   <strong>Crystal Reports, SSRS, BIRT</strong>: Between developing applications and supporting purchased applications I've had to write reports with multiple different report writers. Some have been for in-house written applications (SSRS, Crystal Reports) and some have been used for purchased products (BIRT, SSRS, Crystal Repots).<br/><br/>
   <strong>Power BI</strong>: As software solutions get used more and more this creates a lot more data. In order to be able to provide the data in an easy to use fashion for end users, I've been pulling the data together with Power BI. I created a data warehouse to house the data and have setup Power BI for SQL Server.<br/><br/>
   <strong>IBM Maximo</strong>: I've been the backup support person for Maximo for a few years. I've written reports using BIRT, modified screens using the application designer and worked with using integrations created in the integration framework.<br/><br/>
   <strong>Dynamics SL</strong>: I've been the primary support person for Dynamics SL for most of my career. This work mainly consists of writing reports using Crystal Reports, customizing screens, managing permissions and resolving occasional user problems.<br/><br/>
   <strong>Cornerstone Learning Management System</strong>: I've been the sole IT support person for Cornerstone since it's inception with my current company. The main support work done with this system is providing an integration with the various systems that house our employee data. Some of this comes from our HR/Payroll system and other parts come from Active Directory.<br/><br/>
