# Site settings
title: Spencer Moore
# twitter_username: twitterUsername
name: Spencer Moore

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
# - title: Blog
   #url: http://blogname.blogspot.com/
 - title: GitHub
   url: https://github.com/ProgramMeThis
# - title: StackOverflow
#   url: https://stackoverflow.com/
 - title: LinkedIn
   url: https://www.linkedin.com/in/spencer-moore-7554804

#Any buzzword skills you want to include
skills:
 - C#
 - .Net
 - PowerShell
 - Active Directory
 - BASH Scripting
 - SQL
 - SQL Server
 - BIRT
 - Crystal Reports
 - SSRS
 - Power BI
 - IBM Maximo
 - Microsoft Dynamics SL
 - Cornerstone Learning Management System

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://blogtitle.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Application Support Manager 
   start: 2019
   end: Ongoing
   employer: Grand River Dam Authority
   description: WIP
#   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
 - title: Manager of IT Solution Services 
   start: 2015
   end: 2019
   employer: Grand River Dam Authority
   description: WIP
#   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
 - title: Supt. of Application and Development 
   start: 2013
   end: 2015
   employer: Grand River Dam Authority
   description: WIP   
#   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
 - title: Asst. Supt. Programmer 
   start: 2009
   end: 2013
   employer: Grand River Dam Authority
   description: WIP
#   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Bachelor of Science
   date: 2009
   subject: Information Systems Technology
   school: University of Tulsa

#List of interesting Github repo/projects to include - optional
github:
 - ProgramMeThis/Dell-Warranty-Checker

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/
#   flairimageurl: http://stackoverflow.com/users/flair/

intro: |
  I am a software developer with over 10 years experience working in various facets of IT. Along with developing software I've been managing development/support teams, automating business processes and helping support purchased products such as IBM's Maximo, Microsoft Dynamics SL and Cornerstone Learning Management System. My biggest passion is helping make people's lives easier with the power of technology. Whether that's writing software, buying something off the shelf or simply getting more use out of what you already have there's almost always some room for improvement.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>C#/.Net</strong>: Most of my career has been spent developing applications with .Net and more specifcally C#. The first few years were spent solely developing Windows Forms applications but as web applications became more popular the switch was made to using ASP.net for the primary development platform with some integrations being solved with Windows services. <br/><br/>
   <strong>SQL</strong>: SQL and more specifically SQL Server has been a part of everything I've done in the past 10 years. All of the applications I have developed or pruchased products I have implemented have used SQL server for their backend data storage.<br/><br/>
   <strong>PowerShell</strong>: With part of my time being spent overseeing the help desk along side the software developers, there have been countless times where I've developed a PowerShell script to make the Help Desk more efficient. This ranges from somethign as simple as starting/stopping windows services to completly enabling and setting up BitLocker.<br/><br/>
   <strong>Crystal Reports, SSRS, BIRT</strong>: Between developing applications and supporting purchased applications I've had to write reports with multiple different report writers. Some have been for in-house written applications (SSRS, Crystal Reports) and some have been used for purchased products (BIRT, SSRS, Crystal Repots).<br/><br/>
   <strong>Power BI</strong>: As software solutions get used more and more this creates a lot more data. In order to be able to provide the data in an easy to use fashion for end users, I've been pulling the data together with Power BI. I created a data warehouse to house the data and have setup Power BI for SQL Server.<br/><br/>
   <strong>IBM Maximo</strong>: I've been the backup support person for Maximo for a few years. I've written reports using BIRT, modified screens using the application designer and worked with using integrations created in the integration framework.<br/><br/>
   <strong>Dynamics SL</strong>: I've been the primary support person for Dynamics SL for most of my career. This work mainly consists of writing reports using Crystal Reports, customizing screens, managing permissions and resolving occasional user problems.<br/><br/>
   <strong>Cornerstone Learning Management System</strong>: I've been the sole IT support person for Cornerstone since it's inception with my current company. The main support work done with this system is providing an integration with the various systems that house our employee data. Some of this comes from our HR/Payroll system and other parts come from Active Directory.<br/><br/>
